version: '2'
services:
  jenkins:
    image: jenkinsd
    container_name: "jenkins"
    ports:
    - "8080:8080"
    - "50000:50000"
    volumes:
    - /var/jenkins_home2:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    links:
    - nexus
  nexus:
    image: sonatype/nexus
    container_name: "nexus"
    ports: 
    - "8081:8081"
    volumes:
    - /var/nexus:/sonatype-work

